//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicControlX {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MicControlX.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About MicControlX.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application provides quick and reliable microphone control for users who need instant mute/unmute functionality during calls, streaming, or recording sessions without interrupting their workflow..
        /// </summary>
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disable.
        /// </summary>
        public static string ActionDisable {
            get {
                return ResourceManager.GetString("ActionDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enable.
        /// </summary>
        public static string ActionEnable {
            get {
                return ResourceManager.GetString("ActionEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative Controls.
        /// </summary>
        public static string AlternativeControls {
            get {
                return ResourceManager.GetString("AlternativeControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MicControlX is already running. Check the system tray..
        /// </summary>
        public static string AppAlreadyRunning {
            get {
                return ResourceManager.GetString("AppAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global microphone control utility with hotkey support and system tray integration..
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        public static string ApplicationSettings {
            get {
                return ResourceManager.GetString("ApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MicControlX.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand: .
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates....
        /// </summary>
        public static string CheckingForUpdates {
            get {
                return ResourceManager.GetString("CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed.
        /// </summary>
        public static string DownloadFailed {
            get {
                return ResourceManager.GetString("DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading... {0}.
        /// </summary>
        public static string DownloadingProgress {
            get {
                return ResourceManager.GetString("DownloadingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading update....
        /// </summary>
        public static string DownloadingUpdate {
            get {
                return ResourceManager.GetString("DownloadingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download cancelled by user.
        /// </summary>
        public static string DownloadCancelledByUser {
            get {
                return ResourceManager.GetString("DownloadCancelledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection timeout.
        /// </summary>
        public static string DownloadErrorTimeout {
            get {
                return ResourceManager.GetString("DownloadErrorTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network connection error.
        /// </summary>
        public static string DownloadErrorNetwork {
            get {
                return ResourceManager.GetString("DownloadErrorNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart &amp; Update.
        /// </summary>
        public static string RestartAndUpdate {
            get {
                return ResourceManager.GetString("RestartAndUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again.
        /// </summary>
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Double-click tray icon to open app.
        /// </summary>
        public static string ControlDoubleClick {
            get {
                return ResourceManager.GetString("ControlDoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Right-click tray icon for options.
        /// </summary>
        public static string ControlRightClick {
            get {
                return ResourceManager.GetString("ControlRightClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Single-click system tray icon to toggle.
        /// </summary>
        public static string ControlSingleClick {
            get {
                return ResourceManager.GetString("ControlSingleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2025 Dr. Skinner - GNU General Public License v3.0.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable sound feedback.
        /// </summary>
        public static string EnableSoundFeedback {
            get {
                return ResourceManager.GetString("EnableSoundFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respect Focus Assist (Do Not Disturb).
        /// </summary>
        public static string RespectFocusAssist {
            get {
                return ResourceManager.GetString("RespectFocusAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating About window: {0}...
        /// </summary>
        public static string ErrorAboutWindow {
            get {
                return ResourceManager.GetString("ErrorAboutWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save configuration settings...
        /// </summary>
        public static string ErrorConfigSaveMessage {
            get {
                return ResourceManager.GetString("ErrorConfigSaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Save Error.
        /// </summary>
        public static string ErrorConfigSaveTitle {
            get {
                return ResourceManager.GetString("ErrorConfigSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register the new {0} hotkey...
        /// </summary>
        public static string ErrorHotkeyConflictMessage {
            get {
                return ResourceManager.GetString("ErrorHotkeyConflictMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} hotkey could not be registered...
        /// </summary>
        public static string ErrorHotkeyRegistrationMessage {
            get {
                return ResourceManager.GetString("ErrorHotkeyRegistrationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey Registration Failed.
        /// </summary>
        public static string ErrorHotkeyRegistrationTitle {
            get {
                return ResourceManager.GetString("ErrorHotkeyRegistrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization error: {0}...
        /// </summary>
        public static string ErrorInitializationMessage {
            get {
                return ResourceManager.GetString("ErrorInitializationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadCurrentSettings error: {0}.
        /// </summary>
        public static string ErrorLoadSettingsMessage {
            get {
                return ResourceManager.GetString("ErrorLoadSettingsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception in OkButton_Click: {0}...
        /// </summary>
        public static string ErrorSettingsException {
            get {
                return ResourceManager.GetString("ErrorSettingsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SettingsWindow initialization error: {0}...
        /// </summary>
        public static string ErrorSettingsInitMessage {
            get {
                return ResourceManager.GetString("ErrorSettingsInitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Error.
        /// </summary>
        public static string ErrorSettingsTitle {
            get {
                return ResourceManager.GetString("ErrorSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Failed to {0} Windows startup setting...
        /// </summary>
        public static string ErrorStartupSettingMessage {
            get {
                return ResourceManager.GetString("ErrorStartupSettingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Setting Failed.
        /// </summary>
        public static string ErrorStartupSettingTitle {
            get {
                return ResourceManager.GetString("ErrorStartupSettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Error.
        /// </summary>
        public static string ErrorStartupTitle {
            get {
                return ResourceManager.GetString("ErrorStartupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Error.
        /// </summary>
        public static string StartupError {
            get {
                return ResourceManager.GetString("StartupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Works with any Windows audio device and system settings.
        /// </summary>
        public static string FeatureAnyDevice {
            get {
                return ResourceManager.GetString("FeatureAnyDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Audio feedback with custom sounds.
        /// </summary>
        public static string FeatureAudioFeedback {
            get {
                return ResourceManager.GetString("FeatureAudioFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Automatic startup and background operation.
        /// </summary>
        public static string FeatureAutoStartup {
            get {
                return ResourceManager.GetString("FeatureAutoStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Global hotkey support (F1-F24).
        /// </summary>
        public static string FeatureGlobalHotkey {
            get {
                return ResourceManager.GetString("FeatureGlobalHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Hold hotkey to temporarily mute/unmute.
        /// </summary>
        public static string FeatureHoldHotkey {
            get {
                return ResourceManager.GetString("FeatureHoldHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Multiple OSD notification styles.
        /// </summary>
        public static string FeatureMultipleOSD {
            get {
                return ResourceManager.GetString("FeatureMultipleOSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features:.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features &amp; Compatibility.
        /// </summary>
        public static string FeaturesCompatibility {
            get {
                return ResourceManager.GetString("FeaturesCompatibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • System tray integration with context menu.
        /// </summary>
        public static string FeatureSystemTray {
            get {
                return ResourceManager.GetString("FeatureSystemTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Universal Windows microphone control utility.
        /// </summary>
        public static string FeatureUniversal {
            get {
                return ResourceManager.GetString("FeatureUniversal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Hotkey.
        /// </summary>
        public static string GlobalHotkey {
            get {
                return ResourceManager.GetString("GlobalHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Hotkey:.
        /// </summary>
        public static string GlobalHotkeyLabel {
            get {
                return ResourceManager.GetString("GlobalHotkeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press F11 to toggle, hold to mute/unmute temporarily.
        /// </summary>
        public static string HotkeyInstruction {
            get {
                return ResourceManager.GetString("HotkeyInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press {0} to toggle, hold to mute/unmute temporarily.
        /// </summary>
        public static string HotkeyInstructionTemplate {
            get {
                return ResourceManager.GetString("HotkeyInstructionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotkey Settings.
        /// </summary>
        public static string HotkeySettings {
            get {
                return ResourceManager.GetString("HotkeySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto (System Default).
        /// </summary>
        public static string LanguageAuto {
            get {
                return ResourceManager.GetString("LanguageAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe.
        /// </summary>
        public static string LanguageTurkish {
            get {
                return ResourceManager.GetString("LanguageTurkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        public static string LanguageGerman {
            get {
                return ResourceManager.GetString("LanguageGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone.
        /// </summary>
        public static string Microphone {
            get {
                return ResourceManager.GetString("Microphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone Active.
        /// </summary>
        public static string MicrophoneActive {
            get {
                return ResourceManager.GetString("MicrophoneActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone Muted.
        /// </summary>
        public static string MicrophoneMuted {
            get {
                return ResourceManager.GetString("MicrophoneMuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone Status.
        /// </summary>
        public static string MicrophoneStatus {
            get {
                return ResourceManager.GetString("MicrophoneStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muted.
        /// </summary>
        public static string Muted {
            get {
                return ResourceManager.GetString("Muted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAudio Error.
        /// </summary>
        public static string NAudioError {
            get {
                return ResourceManager.GetString("NAudioError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active microphones found.
        /// </summary>
        public static string NoActiveMicrophones {
            get {
                return ResourceManager.GetString("NoActiveMicrophones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone Active.
        /// </summary>
        public static string NotificationMicrophoneActive {
            get {
                return ResourceManager.GetString("NotificationMicrophoneActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone Muted.
        /// </summary>
        public static string NotificationMicrophoneMuted {
            get {
                return ResourceManager.GetString("NotificationMicrophoneMuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone Temporarily Active.
        /// </summary>
        public static string NotificationMicrophoneTemporarilyActive {
            get {
                return ResourceManager.GetString("NotificationMicrophoneTemporarilyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone Temporarily Muted.
        /// </summary>
        public static string NotificationMicrophoneTemporarilyMuted {
            get {
                return ResourceManager.GetString("NotificationMicrophoneTemporarilyMuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Type.
        /// </summary>
        public static string NotificationType {
            get {
                return ResourceManager.GetString("NotificationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Style.
        /// </summary>
        public static string OSDDefaultStyle {
            get {
                return ResourceManager.GetString("OSDDefaultStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Visual overlay (OSD) initialization failed...
        /// </summary>
        public static string OSDInitializationWarningMessage {
            get {
                return ResourceManager.GetString("OSDInitializationWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSD Initialization Warning.
        /// </summary>
        public static string OSDInitializationWarningTitle {
            get {
                return ResourceManager.GetString("OSDInitializationWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LLT Style.
        /// </summary>
        public static string OSDLLTStyle {
            get {
                return ResourceManager.GetString("OSDLLTStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translucent Style.
        /// </summary>
        public static string OSDTranslucentStyle {
            get {
                return ResourceManager.GetString("OSDTranslucentStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSD Style:.
        /// </summary>
        public static string OSDStyleLabel {
            get {
                return ResourceManager.GetString("OSDStyleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vantage Style.
        /// </summary>
        public static string OSDVantageStyle {
            get {
                return ResourceManager.GetString("OSDVantageStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSD Position:.
        /// </summary>
        public static string OSDPositionLabel {
            get {
                return ResourceManager.GetString("OSDPositionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Left.
        /// </summary>
        public static string OSDTopLeft {
            get {
                return ResourceManager.GetString("OSDTopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Center.
        /// </summary>
        public static string OSDTopCenter {
            get {
                return ResourceManager.GetString("OSDTopCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Right.
        /// </summary>
        public static string OSDTopRight {
            get {
                return ResourceManager.GetString("OSDTopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Center.
        /// </summary>
        public static string OSDMiddleCenter {
            get {
                return ResourceManager.GetString("OSDMiddleCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Left.
        /// </summary>
        public static string OSDBottomLeft {
            get {
                return ResourceManager.GetString("OSDBottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Center.
        /// </summary>
        public static string OSDBottomCenter {
            get {
                return ResourceManager.GetString("OSDBottomCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom Right.
        /// </summary>
        public static string OSDBottomRight {
            get {
                return ResourceManager.GetString("OSDBottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OSD Duration (seconds):.
        /// </summary>
        public static string OSDDurationLabel {
            get {
                return ResourceManager.GetString("OSDDurationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform: .
        /// </summary>
        public static string Platform {
            get {
                return ResourceManager.GetString("Platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone: .
        /// </summary>
        public static string MicrophoneDevice {
            get {
                return ResourceManager.GetString("MicrophoneDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose any OSD style based on your preference - all styles work universally.
        /// </summary>
        public static string RecommendedSettingsDescription {
            get {
                return ResourceManager.GetString("RecommendedSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings error: {0}.
        /// </summary>
        public static string SettingsErrorMessage {
            get {
                return ResourceManager.GetString("SettingsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MicControlX Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show OSD overlay.
        /// </summary>
        public static string ShowOSDOverlay {
            get {
                return ResourceManager.GetString("ShowOSDOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tray notifications.
        /// </summary>
        public static string ShowTrayNotifications {
            get {
                return ResourceManager.GetString("ShowTrayNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start with Windows.
        /// </summary>
        public static string StartWithWindows {
            get {
                return ResourceManager.GetString("StartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Check Error.
        /// </summary>
        public static string StateCheckError {
            get {
                return ResourceManager.GetString("StateCheckError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Information.
        /// </summary>
        public static string SystemInformation {
            get {
                return ResourceManager.GetString("SystemInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Theme:.
        /// </summary>
        public static string ThemeLabel {
            get {
                return ResourceManager.GetString("ThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string ThemeSystem {
            get {
                return ResourceManager.GetString("ThemeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Microphone.
        /// </summary>
        public static string ToggleMicrophone {
            get {
                return ResourceManager.GetString("ToggleMicrophone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MicControlX - Active.
        /// </summary>
        public static string TrayTooltipActive {
            get {
                return ResourceManager.GetString("TrayTooltipActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MicControlX - Muted.
        /// </summary>
        public static string TrayTooltipMuted {
            get {
                return ResourceManager.GetString("TrayTooltipMuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown System.
        /// </summary>
        public static string UnknownSystem {
            get {
                return ResourceManager.GetString("UnknownSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown System - Universal Compatibility Mode.
        /// </summary>
        public static string UnknownSystemDescription {
            get {
                return ResourceManager.GetString("UnknownSystemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You're up to date!.
        /// </summary>
        public static string UpToDate {
            get {
                return ResourceManager.GetString("UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version {0} available. Download now?.
        /// </summary>
        public static string UpdateAvailableMessage {
            get {
                return ResourceManager.GetString("UpdateAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed: {0}.
        /// </summary>
        public static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update check failed.
        /// </summary>
        public static string UpdateCheckFailed {
            get {
                return ResourceManager.GetString("UpdateCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate limited by GitHub. Please try again in an hour..
        /// </summary>
        public static string UpdateErrorRateLimited {
            get {
                return ResourceManager.GetString("UpdateErrorRateLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection available.
        /// </summary>
        public static string UpdateErrorNetworkError {
            get {
                return ResourceManager.GetString("UpdateErrorNetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update repository not accessible.
        /// </summary>
        public static string UpdateErrorNotFound {
            get {
                return ResourceManager.GetString("UpdateErrorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid response from update server.
        /// </summary>
        public static string UpdateErrorInvalidResponse {
            get {
                return ResourceManager.GetString("UpdateErrorInvalidResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update downloaded. Restart to apply?.
        /// </summary>
        public static string UpdateReadyToRestart {
            get {
                return ResourceManager.GetString("UpdateReadyToRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string VersionTemplate {
            get {
                return ResourceManager.GetString("VersionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}